version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Mapea el puerto del contenedor al puerto local
    volumes:
      - ./frontend:/meetEase-frontend
      - /meetEase-frontend/node_modules
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:3000  # Comunicación entre contenedores de Docker
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Exponer backend en el puerto 3000
    volumes:
      - ./backend:/meetEase-backend
      - /meetEase-backend/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FRONTEND_ORIGIN=http://localhost:5173  # Este es el origen esperado del frontend
      - DATABASE_URI=postgresql://postgres.lxukewbgbwdohusjgqlo:23272412rcs9@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
      - JWT_SECRET=74e567d6ad3fafe9a1dc637030da24d21eefd5623484e63cbae7afdc38c7f2db0530c8ee450cc63dee3abb577a09822a0f4b70f0913ce67abd32bcbecf54c281
