name: Deploy Frontend and Backend to Render

on:
  push:
    branches:
      - main 
  workflow_dispatch: # Permite disparar el workflow manualmente desde GitHub UI

jobs:
  # Job para el despliegue del Backend
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (o tu runtime de backend, e.g., Python, Java)
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajusta la versión de Node.js según tu backend

      - name: Install backend dependencies
        working-directory: ./backend # Ruta a tu carpeta de backend
        run: npm install # O pip install -r requirements.txt, mvn install, etc.

      - name: Build backend (si es necesario)
        working-directory: ./backend # Ruta a tu carpeta de backend
        run: npm run build # Algunos backends no necesitan un paso de 'build'

      - name: Trigger Backend Deploy on Render
        uses: JorgeLNJunior/render-deploy@v1.4.5 # Usa la acción de Render
        with:
          service_id: ${{ secrets.BACKEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true 
          wait_deploy: true 

  # Job para el despliegue del Frontend
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend # Este job esperará a que el backend se despliegue primero
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajusta la versión de Node.js según tu frontend

      - name: Install frontend dependencies
        working-directory: ./frontend # Ruta a tu carpeta de frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend # Ruta a tu carpeta de frontend
        run: npm run build # Ajusta este comando si usas otra herramienta (e.g., yarn build, ng build)

      - name: Trigger Frontend Deploy on Render
        uses: JorgeLNJunior/render-deploy@v1.4.5 # Usa la acción de Render
        with:
          service_id: ${{ secrets.FRONTEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true 
          wait_deploy: true 
