name: Run Vitest tests

on:
  push:
    branches: [main, master, GRP]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Vitest
        run: npx vitest run
        working-directory: ./frontend
